config/routes.rb
Rails.application.routes.draw do
  get 'uploads/index'
  get 'uploads/format'
  get 'uploads/status/:document_id', to: 'uploads#status', as: 'uploads_status'

  root 'uploads#index'
end

app/models/document.rb
class Document < ActiveRecord::Base

  def format
    sleep 5
    update_column :imported, true
  end

  handle_asynchronously :format

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController

  def index

  end

  def format
    @doc = Document.create(name: 'Invisible')
    @doc.format
  end

  def status
    @doc = Document.find(params[:document_id])
    render json: { id: @doc.id, imported: @doc.imported }
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DelayedTuto</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/uploads/format.html.erb
<!-- views/uploads/format.html.erb -->
<div data-status="<%= uploads_status_path(@doc) %>">
  <p>Formatting...</p>
  <%= link_to 'Back', root_path, style: 'display: none;' %>
</div>

app/views/uploads/index.html.erb
<!-- views/uploads/index.html.erb -->
<h1>Upload</h1>
<%= link_to 'Upload & Format an invisible file !', uploads_format_path %>